### PR TITLE
Add integration test

### PR DESCRIPTION
**Pull request by wuchih-amazon**
Thanks for contributing to DLR! By submitting this pull request, you confirm that your contribution is made under the terms of the [Apache 2.0 license](https://github.com/neo-ai/neo-ai-dlr/blob/master/LICENSE).

Please refer to our [guideline](https://github.com/neo-ai/neo-ai-dlr/blob/master/CONTRIBUTING.md) for useful information and tips.

### CODE REVIEW

**Comment by wuchih-amazon** [comment]
@dkasar-aws  can you review this? I'd like to add integration test for this

**Comment by dkasar-aws** [comment]
> 
> 
> @dkasar-aws can you review this? I'd like to add an integration test for this

The test case seems more like a unit test instead an integration test case. Similar unit test cases (Pytest) already available in <DLR Repo>/tests/python/unittest.
I tried to execute it with the latest changes of "prod-countermgr" PR and seems working fine, no Hang observed. (the test case wait only configured wait time i.e. 300 sec after that it should exit.)

**Comment by wuchih-amazon** [comment]
> > @dkasar-aws can you review this? I'd like to add an integration test for this
> 
> The test case seems more like a unit test instead an integration test case. Similar unit test cases (Pytest) already available in /tests/python/unittest.
> I tried to execute it with the latest changes of "prod-countermgr" PR and seems working fine, no Hang observed. (the test case wait only configured wait time i.e. 300 sec after that it should exit.)

It's not a microscopic focus on unit testing, but I'd like to see what happen if actual device user load the DLR on their devices. The given script is a sample use case of DLR, which we don't have any test case as yet.

In this case scenario, I'm only testing if proper notification is printing, which it's not in an unit test as well.

**Comment by wuchih-amazon** [comment]
> > @dkasar-aws can you review this? I'd like to add an integration test for this
> 
> The test case seems more like a unit test instead an integration test case. Similar unit test cases (Pytest) already available in /tests/python/unittest.
> I tried to execute it with the latest changes of "prod-countermgr" PR and seems working fine, no Hang observed. (the test case wait only configured wait time i.e. 300 sec after that it should exit.)

In addition, what's actual purpose of sleep? It seems to me that you're doing this to throttle the put. However, when user application ended, it will still wait for 5 minutes before their application to shutdown. This is still not the behavior that we hope to achieve. Is there a better approach to do throttling? or perhaps interrupt the timeout when user exit their application?

**Comment by wuchih-amazon** [comment]
If there is no objection towards this, please merge this in

**Pull request merged**
